# Generated by Django 3.0.3 on 2020-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='completed_wathcing_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='started_wathcing_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
