# Generated by Django 3.0.3 on 2020-02-28 21:07

from django.db import migrations, models
import tv.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20200227_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=tv.models.get_file_path),
        ),
    ]
