# Generated by Django 3.0.3 on 2020-02-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv', '0004_shows_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to=settings.AUTH_USER_MODEL),
        ),
    ]
