# Generated by Django 3.0.3 on 2020-02-28 21:07

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=games.models.get_file_path),
        ),
    ]
