# Generated by Django 3.0.3 on 2020-02-28 21:07

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-completed_watching_on'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=movies.models.get_file_path),
        ),
    ]
